# vim:ts=2:sw=2:et:ft=yaml:
options:
  grok_src:
    type: string
    default: /var/opengrok/src
    description: Location where user supplied code lives, always preserved.

  grok_data:
    type: string
    default: /var/opengrok/data
    description: Location where opengrok generated indexes live.

  preserve_grok_indexes:
    type: boolean
    default: True
    description: on charm-upgrade, preserve contents of $grok_data.
      NOTE indexes are always destroyed during install to ensure a sane environment.

  og_content:
    default: '{
      "repos":[
        {
          "url"   : "lp:juju",
          "alias" : "juju"
        }
       ]
    }'
    type: string
    description: |
      List of launchpad only repositories (lp:) using JSON arrays for opengrok to pull
      and index once. Example syntax:

        og_content='{
          "repos":[
            { "url"   : "lp:juju", "alias" : "juju"},
            {..., ...},
            {..., ...}
          ]
       }'

      Where url is the repo link and alias is the directory name to create on it's
      behalf, both must be set.
