# vim:ts=2:sw=2:et:ft=yaml:
options:
  og-content:
    default: '{
      "repos":[
        {
          "url"   : "lp:juju",
          "alias" : "juju"
        },

        {
          "url"   : "lp:ubuntu/multipath-tools",
          "alias" : "multipath"
        },

        {
          "url"   : "git:foo",
          "alias" : "bar"
        },

        {
          "url"   : "lp:grub",
          "alias" : "grubby"
        }

       ]
    }'

    type: string
    description: |
      List of launchpad only repositories (lp:) using JSON arrays for opengrok to pull
      and index once. Example syntax:

        XXX fix the quoting
        og-content=[{ 'url' : 'lp:juju', 'alias' : 'juju'}, {...}]

      Where url is the repo link and alias is the directory name to create on it's
      behalf. 'alias' can be value null in which case the default repo dir is used.
      Alias is necessary for branches of the form series/project/trunk, which will
      create a repo name of trunk
