# vim:ts=2:sw=2:et:ft=yaml:
options:
  grok_src:
    type: string
    default: /var/opengrok/src
    description: Location where user supplied code lives, always preserved.

  grok_data:
    type: string
    default: /var/opengrok/data
    description: Location where opengrok generated indexes live.

  preserve_grok_indexes:
    type: boolean
    default: True
    description: on charm-upgrade, preserve contents of $grok_data.
      NOTE indexes are always destroyed during install to ensure a sane environment.

  og_content:
    default: '{
      "repos":[
        {
          "url"   : "lp:juju",
          "alias" : "juju"
        },

        {
          "url"   : "lp:ubuntu/multipath-tools",
          "alias" : "multipath"
        },

        {
          "url"   : "git://github.com/ppetraki/cisco-fc-failover.git",
          "alias" : "cisco-fc-failover"
        },

        {
          "url"   : "lp:grub",
          "alias" : "grubby"
        }

       ]
    }'

    type: string
    description: |
      List of launchpad only repositories (lp:) using JSON arrays for opengrok to pull
      and index once. Example syntax:

        XXX fix the quoting
        og_content=[{ 'url' : 'lp:juju', 'alias' : 'juju'}, {...}]

      Where url is the repo link and alias is the directory name to create on it's
      behalf. 'alias' can be value null in which case the default repo dir is used.
      Alias is necessary for branches of the form series/project/trunk, which will
      create a repo name of trunk
