#!/bin/bash
set -eux
# TODO 
# * idempontent
# * rework to switch/case "common script" with symlink architecture
# * create hook to integrate with existing tomcat6 service.
# * parameterize opengrok config at runtime
# * attach and manage persistant storage for src & data

tarball=opengrok-0.11.1.tar.gz
grokjar=http://hub.opensolaris.org/bin/download/Project+opengrok/files/${tarball}

juju-log "Preparing to install OpenGrok"
export DEBIAN_FRONTEND=noninteractive
apt-get -q -y install tomcat6 exuberant-ctags wget bzr

juju-log "Installing opengrok 11.1 JAR from tarball"
pushd /opt
wget ${grokjar} 2>/dev/null
tar xzvf ${tarball}
ln -s opengrok-0.11.1 opengrok
popd

juju-log "deploying opengrok war to servlet root"
# deploy script scans for common servlets and had hardcoded paths
# should you use tomcat7 this will probably not work.
pushd /opt/opengrok/bin
./OpenGrok deploy
popd

juju-log "creating opengrok src and data store"
mkdir -p /var/opengrok/src /var/opengrok/data

juju-log "acquiring example source code: juju"
pushd /var/opengrok/src
bzr branch lp:juju 2>/dev/null
popd

juju-log "indexing..."
pushd /opt/opengrok/bin
./OpenGrok index
popd

open-port 8080/tcp

juju-log "opengrok installed, expose service and visit http://HOSTIP:8080/source"
