#!/bin/bash
set -eux #-x for verbose logging to juju debug-log

install_opengrok_cronjob()
{
    # unconditionally update this script
    rm -f /etc/cron.daily/opengrok || :
    tee /etc/cron.daily/opengrok << EOF
#!/bin/sh
cd /opt/opengrok/bin && ./OpenGrok update
EOF
    chmod +x /etc/cron.daily/opengrok
}


tarball=opengrok-0.11.1+ubuntu1.tar.gz
tarball_sha256=8ae34f00bd2bf672b7cea2868d9de5fafe7c00ba03c869bad6996dcaaa0e522d
#grokjar=http://hub.opensolaris.org/bin/download/Project+opengrok/files/${tarball}
grokjar=http://people.canonical.com/~ppetraki/charms/opengrok/${tarball}

groksrc=/var/opengrok/src
grokdata=/var/opengrok/data
groketc=/var/opengrok/etc

juju-log "Preparing to install OpenGrok"
add-apt-repository -y ppa:charmers/charm-helpers
apt-get update
apt-get -qqy install tomcat6 exuberant-ctags bzr charm-helper-sh

juju-log "Installing opengrok 11.1 JAR from tarball"
. /usr/share/charm-helper/sh/net.sh
templocation=`ch_get_file ${grokjar} ${tarball_sha256}`

rm -rf /opt/opengrok*
tar xzf ${templocation} -C /opt
basedir=$(echo ${tarball} | perl -ne '@F = split(".tar.gz",$_); print("$F[0]");')
ln -s /opt/${basedir} /opt/opengrok

juju-log "deploying opengrok war to servlet root"
# deploy script scans for common servlets and had hardcoded paths
# should you use tomcat7 this will probably not work.
cd /opt/opengrok/bin && ./OpenGrok deploy

juju-log "creating opengrok src and data store"
mkdir -p ${groksrc}

# if data/ already exists, wipe it out unconditionally (for now)
# index could be corrupted and we wish to ensure the service
# is in the best possible state to run the first time.
[ -d "${grokdata}" ] && rm -rf ${grokdata}
mkdir -p ${grokdata}

# Same goes for local configuration
[ -d "${groketc}" ] && rm -rf ${groketc}
mkdir -p ${groketc}

juju-log "acquiring example source code: juju"
demo_src=/var/opengrok/src/juju

if [ ! -d "${demo_src}" ]
then
    bzr branch lp:juju ${demo_src} 2>/dev/null
else
    if [ -d "${demo_src}/.bzr" ]
    then
        juju-log "juju sandbox exists, updating"
        cd ${demo_src} && bzr pull --overwrite
        cd ${demo_src} && bzr update
    fi
fi

juju-log "Installing daily cron job"
install_opengrok_cronjob

juju-log "indexing..."
# XXX for whatever reason, the first time an index is built opengrok
# insist's on building an index for the history, which always fails.
# On subsequent runs however, it honors the lack of a -H switch. So
# the workaround for setting up new projects is to run update twice.
. /etc/cron.daily/opengrok || :
OPENGROK_VERBOSE=1 . /etc/cron.daily/opengrok

open-port 8080/tcp

juju-log "opengrok installed, expose service and visit http://HOSTIP:8080/source"

# vim:ts=4:sw=4:et:
